[tool.poetry]
name = "lintastic"
version = "0.1.0"
description = "CLI to validate YAML and JSON documents"
authors = ["Renan Morais <renan.ps.morais@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
